title: "Rachel Lee"
author: "Rachel Lee"
description: "Teachers College, Columbia University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "stats.html", title: Statistics}
  - {file: "ML.md", title: Machine Learning}
  - {file: "index.html", title: Home Change, icon: home}
  - {file: "README.md", title: About me, icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yl3751@tc.columbia.edu"}
  - {title: Github, icon: github, url: "https://github.com/leerachel20"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
